package org.aurora.protocol.android.core

internal enum class CoreOperation(val wireValue: Int) {
    CLOSE_NATIVE_SESSION(10),
    INGRESS_LOCAL_PACKET(14),
    NEXT_LOCAL_PACKET(15),
    BEGIN_NATIVE_SESSION_JSON(16),
    COMPLETE_NATIVE_SESSION_RAW(17),
    RESERVE_NATIVE_PROVISIONING(19),
    CONFIGURE_NATIVE_PROVISIONING_TRUST(21),
}
